# Generated by Django 3.0.7 on 2020-06-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_name',
            new_name='form_name',
        ),
    ]
