# Generated by Django 3.0.7 on 2020-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200608_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='training_id',
            new_name='form_id',
        ),
        migrations.AlterField(
            model_name='training',
            name='form_name',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='training',
            name='user_id',
        ),
        migrations.AddField(
            model_name='training',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
