# Generated by Django 3.0.7 on 2020-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200608_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='form_id',
            field=models.CharField(max_length=20),
        ),
    ]
