# Generated by Django 3.0.7 on 2020-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200608_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_id', models.IntegerField()),
                ('lobby_name', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Date', models.DateField(null=True)),
                ('user_id', models.ManyToManyField(to='pages.users')),
            ],
        ),
    ]
