# Generated by Django 3.0.7 on 2020-06-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_lobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='City',
            new_name='city',
        ),
    ]
